
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author udesh
 */
public class issuru_book extends javax.swing.JFrame {

    /**
     * Creates new form issuru_book
     */
    public issuru_book() {
        initComponents();
        screensize();
        un.setEditable(false);
        txtisd.setEditable(false);
        txtred.setEditable(false);
        txtum.setVisible(false);
        txtb1.setText("BI");
        txtb1.grabFocus();
        
        
       
        try {
            Image icone = Toolkit.getDefaultToolkit().getImage("C:\\Users\\udesh\\Pictures\\loicone.jpg");
            setIconImage(icone);
        } catch (Exception e) {
        }
    }

    private void screensize() {

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtb2 = new javax.swing.JTextField();
        txtred = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtisd = new javax.swing.JTextField();
        txtmi = new javax.swing.JTextField();
        txtb1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtum = new javax.swing.JButton();
        un = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1616, 32, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("  BOOK ISSURE");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 460, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("User ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 360, 50));

        jLabel15.setBackground(new java.awt.Color(0, 0, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("  Return Date(DD-MM-YYYY)");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 360, 50));

        jLabel6.setBackground(new java.awt.Color(0, 0, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("  BOOK ID");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 360, 70));

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("  Issued Date(DD-MM-YYYY)");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 360, 50));

        txtb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtb2ActionPerformed(evt);
            }
        });
        txtb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtb2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtb2KeyTyped(evt);
            }
        });
        getContentPane().add(txtb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 350, 30));

        txtred.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtredActionPerformed(evt);
            }
        });
        getContentPane().add(txtred, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 360, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("02.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 40, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("01.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, 30));

        txtisd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtisd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 360, 50));

        txtmi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmiActionPerformed(evt);
            }
        });
        txtmi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmiKeyTyped(evt);
            }
        });
        getContentPane().add(txtmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 360, 50));

        txtb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtb1ActionPerformed(evt);
            }
        });
        txtb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtb1KeyTyped(evt);
            }
        });
        getContentPane().add(txtb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 350, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Member_id");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 250, 50));

        txtid.setBackground(new java.awt.Color(51, 51, 51));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 102));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 210, 30));

        jButton1.setBackground(new java.awt.Color(0, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setText("      ISSURE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 310, 60));

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText(" Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        txtum.setBackground(new java.awt.Color(0, 102, 102));
        txtum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtum.setText("Update ");
        txtum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtumActionPerformed(evt);
            }
        });
        getContentPane().add(txtum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 320, 260, 50));

        un.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        getContentPane().add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 360, 50));

        jLabel7.setBackground(new java.awt.Color(0, 0, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("User Name");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 360, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\udesh\\Pictures\\s.jpg")); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -60, 1760, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new mainmenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed

    }//GEN-LAST:event_unActionPerformed

    private void txtredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtredActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String book_id1 = txtb1.getText().toUpperCase();
            String book_id2 = txtb2.getText().toUpperCase();
            String member_id = txtmi.getText().toUpperCase();
            String name = un.getText().toUpperCase();
            String issuru_date = txtisd.getText();
            String retun_date = txtred.getText();
          db.iud("insert into issure_book values('" + book_id1 + "','" + book_id2 + "','" + member_id + "','" + name + "','" + issuru_date +  "','"+retun_date+"','"+1+"')");
          ResultSet rs = db.serch("select (qty) from book_infro where book_id ='"+book_id1+"'");
          if(rs.next()){
            ResultSet rs1 = db.serch("select (qty) from book_infro where book_id ='"+book_id2+"'");
            if(rs1.next()){
            
            int qty =rs.getInt("qty")-1;
               int qty1 =rs1.getInt("qty")-1;
            db.iud("update book_infro set qty='"+qty+"'where book_id='"+book_id1+"'");
            db.iud("update book_infro set qty='"+qty1+"'where book_id='"+book_id2+"'");
             JOptionPane.showMessageDialog(this, "book issuru successfull");
            
            }
            
          }
         
          
        } catch (Exception e) {
            e.printStackTrace();

        }
         txtb1.setText(null);
             txtb2.setText(null);
             txtmi.setText(null);
            un.setText(null);
             txtisd.setText(null);
             txtred.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmiActionPerformed
        try {
            ResultSet serch = db.serch("select (name)from member_register where member_id='" + txtmi.getText().toUpperCase() + "'");
            if (serch.next()) {
                un.setText(serch.getString("name"));
                
        String issued_date = new SimpleDateFormat("yyyy-MM-dd ").format(new Date());
        txtisd.setText(issued_date);

        Calendar calender = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        calender.add(Calendar.DATE, 30);
        txtred.setText(sdf.format(calender.getTime()));
             
                
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_txtmiActionPerformed

    private void txtb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtb2ActionPerformed
         txtmi.setText("E");
         txtmi.grabFocus();
    }//GEN-LAST:event_txtb2ActionPerformed

    private void txtumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtumActionPerformed
       try {

           String book_id1 = txtb1.getText().toUpperCase();
            String book_id2 = txtb2.getText().toUpperCase();
            String member_id = txtmi.getText().toUpperCase();
            String name = un.getText().toUpperCase();
            String issuru_date = txtisd.getText();
            String retun_date = txtred.getText();
            db.iud("update issure_book set book_id1='"+book_id1+"',book_id2='"+book_id2+"',member_id='"+member_id+"',name='"+name+"',issuru_date='"+issuru_date+"',retun_date='"+retun_date+"' where member_id='"+txtmi.getText()+"'");
            JOptionPane.showMessageDialog(this, "Successfully update!!");

        } catch (Exception e) {
            e.printStackTrace();
        }
       txtb1.setText(null);
             txtb2.setText(null);
             txtmi.setText(null);
            un.setText(null);
             txtisd.setText(null);
             txtred.setText(null);
             
              txtum.setVisible(false);
    }//GEN-LAST:event_txtumActionPerformed

    private void txtb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtb1ActionPerformed
        txtb2.setText("BI");
        txtb2.grabFocus();
    }//GEN-LAST:event_txtb1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ResultSet serch = db.serch("select * from issure_book where member_id='"+txtid.getText().toUpperCase()+"'");

            if(serch.next()){
               txtum.setVisible(true);
                txtb1.setText(serch.getString("book_id1"));
                txtb2.setText(serch.getString("book_id2"));
                txtmi.setText(serch.getString("member_id"));
                un.setText(serch.getString("name"));
                txtisd.setText(serch.getString("issuru_date"));
                txtred.setText(serch.getString("retun_date"));
               
                

            }
            txtid.setText(null);

        } catch (Exception e) {
            e.printStackTrace();
        }
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
          txtmi.grabFocus();
    }//GEN-LAST:event_txtidActionPerformed

    private void txtb2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtb2KeyPressed
       
    }//GEN-LAST:event_txtb2KeyPressed

    private void txtb1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtb1KeyTyped
       if(txtb1.getText().length()==7){
        evt.consume();
      }
       if(txtb1.getText().toUpperCase().contains("BI")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }

    }//GEN-LAST:event_txtb1KeyTyped

    private void txtb2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtb2KeyTyped
        if(txtb2.getText().length()==7){
        evt.consume();
      }
       if(txtb2.getText().toUpperCase().contains("BI")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }

    }//GEN-LAST:event_txtb2KeyTyped

    private void txtmiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmiKeyTyped
         if(txtmi.getText().length()==7){
        evt.consume();
      }
       if(txtmi.getText().toUpperCase().contains("E")){
           char keyChar = evt.getKeyChar();
        boolean isDigit = Character.isDigit(keyChar);
        if(!isDigit){
        evt.consume();
        }
      }
    }//GEN-LAST:event_txtmiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuru_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuru_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuru_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuru_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuru_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField txtb1;
    private javax.swing.JTextField txtb2;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtisd;
    private javax.swing.JTextField txtmi;
    private javax.swing.JTextField txtred;
    private javax.swing.JButton txtum;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
